/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import model.ThanhVien;

/**
 *
 * @author Tran Chuyen
 */
public class HCNSFrm extends javax.swing.JFrame {

    private ThanhVien thanhVien;
    public HCNSFrm(ThanhVien thanhVien) {
        initComponents();
        this.thanhVien = thanhVien;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelRoot = new javax.swing.JPanel();
        btnDKLam = new javax.swing.JButton();
        btnXemLich = new javax.swing.JButton();
        btnCICO = new javax.swing.JButton();
        btnTinhLuong = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnTraLuong = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(128, 191, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelRoot.setBackground(new java.awt.Color(179, 217, 255));

        btnDKLam.setBackground(new java.awt.Color(255, 255, 255));
        btnDKLam.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnDKLam.setForeground(new java.awt.Color(76, 175, 80));
        btnDKLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reading.png"))); // NOI18N
        btnDKLam.setText("Đăng Ký Làm");
        btnDKLam.setBorder(null);
        btnDKLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKLamActionPerformed(evt);
            }
        });

        btnXemLich.setBackground(new java.awt.Color(255, 255, 255));
        btnXemLich.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnXemLich.setForeground(new java.awt.Color(76, 175, 80));
        btnXemLich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/board.png"))); // NOI18N
        btnXemLich.setText("Xem Lịch");
        btnXemLich.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnXemLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLichActionPerformed(evt);
            }
        });

        btnCICO.setBackground(new java.awt.Color(255, 255, 255));
        btnCICO.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnCICO.setForeground(new java.awt.Color(76, 175, 80));
        btnCICO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hand.png"))); // NOI18N
        btnCICO.setText("CICO");
        btnCICO.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnCICO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCICOActionPerformed(evt);
            }
        });

        btnTinhLuong.setBackground(new java.awt.Color(255, 255, 255));
        btnTinhLuong.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnTinhLuong.setForeground(new java.awt.Color(76, 175, 80));
        btnTinhLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/money-bag.png"))); // NOI18N
        btnTinhLuong.setText("Tính Lương");
        btnTinhLuong.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(232, 64, 60));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_menu0_white_24dp.png"))); // NOI18N
        jLabel2.setText("TRANG CHỦ HCNS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        btnTraLuong.setBackground(new java.awt.Color(255, 255, 255));
        btnTraLuong.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnTraLuong.setForeground(new java.awt.Color(76, 175, 80));
        btnTraLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hand.png"))); // NOI18N
        btnTraLuong.setText("Trả Lương");
        btnTraLuong.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnTraLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRootLayout = new javax.swing.GroupLayout(jPanelRoot);
        jPanelRoot.setLayout(jPanelRootLayout);
        jPanelRootLayout.setHorizontalGroup(
            jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelRootLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCICO, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTinhLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDKLam, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                        .addComponent(btnXemLich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnTraLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRootLayout.setVerticalGroup(
            jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRootLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnDKLam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnXemLich, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnTinhLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnCICO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnTraLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDKLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKLamActionPerformed
        // TODO add your handling code here:
        ChonTuanFrm chonTuanFrm = new ChonTuanFrm(thanhVien);
        this.dispose();
        chonTuanFrm.setVisible(true);
        chonTuanFrm.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnDKLamActionPerformed

    private void btnXemLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLichActionPerformed
        // TODO add your handling code here:
        this.dispose();
//        TimLopFrm tl = new TimLopFrm(id);
//        tl.setVisible(true);
//        tl.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnXemLichActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        xacNhanThoat();
    }//GEN-LAST:event_formWindowClosing

    private void btnCICOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCICOActionPerformed
        // TODO add your handling code here:
        this.dispose();
//        TimLopDiemDanhFrm tl = new TimLopDiemDanhFrm(id);
//        tl.setVisible(true);
//        tl.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnCICOActionPerformed

    private void btnTraLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTraLuongActionPerformed

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TimNhanVienFrm timNhanVienFrm = new TimNhanVienFrm(thanhVien,-1);
        timNhanVienFrm.setVisible(true);
        timNhanVienFrm.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnTinhLuongActionPerformed
     private void xacNhanThoat(){
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kQ = JOptionPane.showConfirmDialog(null,
                "Bạn có muốn thoát chương trình không ?","Confirm",JOptionPane.YES_NO_OPTION);
        if(kQ == 0){
            System.exit(0);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCICO;
    private javax.swing.JButton btnDKLam;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JButton btnTraLuong;
    private javax.swing.JButton btnXemLich;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRoot;
    // End of variables declaration//GEN-END:variables
}
